language: go

go:
    - master
    - 1.9.x

install:
    - go get -u -v github.com/go-task/task/cmd/task
    - go get -u -v github.com/jteeuwen/go-bindata/...
    - go get -u -v github.com/elazarl/go-bindata-assetfs/...
    - go get -u github.com/golang/dep/cmd/dep

script:
    - dep ensure
    - task build
    - go test ./grammar/... ./lexer/...
