language: go

go:
    - master
    - 1.9.x

install:
    - go get -u -v github.com/go-task/task/cmd/task
    - task install

script:
    - dep ensure
    - task build
    - go test ./grammar/... ./lexer/...
