test:
    deps: [dependencies]
    cmds:
        - go test ./grammar/... ./lexer/...
test-v:
    deps: [dependencies]
    cmds:
        - go test -v ./grammar/... ./lexer/...
 
build:
    deps: [dependencies, assets]
    cmds:
        - go install

dependencies:
    cmds:
        - dep ensure

cover-grammar:
    cmds:
        - go test -coverprofile=coverage.out ./grammar/...

cover-lexer:
    cmds:
        - go test -coverprofile=coverage.out ./lexer/...

view-cover:
    cmds:
        - go tool cover -func=coverage.out

browser-cover:
    cmds:
        - go tool cover -html=coverage.out

assets:
    cmds:
        - cd web && yarn install
        - cd web && yarn build
        - go-bindata-assetfs -pkg parserhttp ./web/dist/...
        - mv bindata_assetfs.go parserhttp/
