test:
    cmds:
        - go test -coverprofile=coverage.out ./grammar/...
 
build:
    cmds:
        - go generate ./...
        - go build .

view-cover:
    cmds:
        - go tool cover -func=coverage.out

browser-cover:
    cmds:
        - go tool cover -html=coverage.out
