test:
    cmds:
        - go test ./grammar/... ./lexer/...
 
build:
    cmds:
        - go generate ./...
        - go build .

view-cover:
    cmds:
        - go tool cover -func=coverage.out

browser-cover:
    cmds:
        - go tool cover -html=coverage.out
