test:
    cmds:
        - go test ./grammar/... ./lexer/...
test-v:
    cmds:
        - go test -v ./grammar/... ./lexer/...
 
build:
    cmds:
        - go generate ./...
        - go build .

cover-grammar:
    cmds:
        - go test -coverprofile=coverage.out ./grammar/...

cover-lexer:
    cmds:
        - go test -coverprofile=coverage.out ./lexer/...

view-cover:
    cmds:
        - go tool cover -func=coverage.out

browser-cover:
    cmds:
        - go tool cover -html=coverage.out
